/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fit5042.gui;

import fit5042.duopan.BankSystem;
import fit5042.duopan.repository.entities.User;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author duopan
 */
public class MyInfo extends javax.swing.JFrame
{

    DefaultComboBoxModel<String> typesModel; 
    
    /**
     * Creates new form MyInfo
     */
    public MyInfo()
    {
        String[] typeStrings = new String[] {"Public","Bank Worker"};
        typesModel = new DefaultComboBoxModel(typeStrings);
        
        initComponents();
        setClose();
        setMyInfo();
    }
    
    private void setClose()
    {
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new WindowAdapter()
        {
            @Override
            public void windowClosing(WindowEvent e)
            {
                backToMainPage();
            }
        });
    }

    private void backToMainPage()
    {
        if (jComboBoxType.getSelectedIndex() == 0)
        {
            MainFrame mainFrame = new MainFrame();
            mainFrame.setVisible(true);
        }
        else
        {
            AdminFrame adFrame = new AdminFrame();
            adFrame.setVisible(true);
        }
        this.dispose();
    }
    
    private void setMyInfo()
    {
        User u = BankSystem.getInstance().getLoginUser();
        jTextFieldId.setText(Integer.toString(u.getUserId()));
        jTextFieldFN.setText(u.getFirstName());
        jTextFieldLN.setText(u.getLastName());
        jTextFieldEmail.setText(u.getEmail());
        jTextFieldPsw.setText(u.getPassword());
        jTextFieldPhone.setText(u.getPhone());
        jTextFieldBalance.setText(Float.toString(u.getBalance()));
        jTextFieldAddress.setText(u.getAddress());
        if (u.getType().equals("Public"))      
            jComboBoxType.setSelectedIndex(0);
        else
            jComboBoxType.setSelectedIndex(1);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel4 = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldFN = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldLN = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldPsw = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxType = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldBalance = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldPhone = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldAddress = new javax.swing.JTextField();
        jButtonCancel = new javax.swing.JButton();
        jButtonSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Personal Information");
        getContentPane().setLayout(new java.awt.GridLayout(0, 2));

        jLabel4.setText("User ID");
        getContentPane().add(jLabel4);

        jTextFieldId.setEditable(false);
        getContentPane().add(jTextFieldId);

        jLabel2.setText("First Name");
        getContentPane().add(jLabel2);
        getContentPane().add(jTextFieldFN);

        jLabel3.setText("Last Name");
        getContentPane().add(jLabel3);
        getContentPane().add(jTextFieldLN);

        jLabel5.setText("Email");
        getContentPane().add(jLabel5);
        getContentPane().add(jTextFieldEmail);

        jLabel6.setText("Password");
        getContentPane().add(jLabel6);
        getContentPane().add(jTextFieldPsw);

        jLabel7.setText("Type");
        getContentPane().add(jLabel7);

        jComboBoxType.setModel(typesModel);
        jComboBoxType.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jComboBoxTypeActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxType);

        jLabel8.setText("Balance");
        getContentPane().add(jLabel8);

        jTextFieldBalance.setEditable(false);
        getContentPane().add(jTextFieldBalance);

        jLabel9.setText("Phone Number");
        getContentPane().add(jLabel9);
        getContentPane().add(jTextFieldPhone);

        jLabel10.setText("Address");
        getContentPane().add(jLabel10);
        getContentPane().add(jTextFieldAddress);

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonCancelActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancel);

        jButtonSave.setText("Save");
        jButtonSave.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonSaveActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSave);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxTypeActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jComboBoxTypeActionPerformed
    {//GEN-HEADEREND:event_jComboBoxTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTypeActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonCancelActionPerformed
    {//GEN-HEADEREND:event_jButtonCancelActionPerformed
        backToMainPage();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonSaveActionPerformed
    {//GEN-HEADEREND:event_jButtonSaveActionPerformed
        if (!jTextFieldFN.getText().matches("[a-zA-Z]+") || !jTextFieldLN.getText().matches("[a-zA-Z]+"))
        {
            JOptionPane.showMessageDialog(null, "Name Must Be Letters!", "Waring", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        if (!jTextFieldEmail.getText().matches("[\\w\\.-]*[a-zA-Z0-9_]@[\\w\\.-]*[a-zA-Z0-9]\\.[a-zA-Z][a-zA-Z\\.]*[a-zA-Z]") )
        {
            JOptionPane.showMessageDialog(null, "Wrong Email Format!", "Waring", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        if (!jTextFieldPhone.getText().matches("^(9\\d{7})|(0\\d{9})$"))
        {
            JOptionPane.showMessageDialog(null, "Wrong Phone Number Format!", "Waring", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        BankSystem.getInstance().getLoginUser().setEmail(jTextFieldEmail.getText());
        BankSystem.getInstance().getLoginUser().setAddress(jTextFieldAddress.getText());
        BankSystem.getInstance().getLoginUser().setFirstName(jTextFieldFN.getText());
        BankSystem.getInstance().getLoginUser().setLastName(jTextFieldLN.getText());
        BankSystem.getInstance().getLoginUser().setPassword(jTextFieldPsw.getText());
        BankSystem.getInstance().getLoginUser().setPhone(jTextFieldPhone.getText());
        BankSystem.getInstance().getLoginUser().setType(jComboBoxType.getSelectedItem().toString());
        
        BankSystem.getInstance().updateInfo(0);
        
        JOptionPane.showMessageDialog(null, "Update Successfully!", "Waring", JOptionPane.INFORMATION_MESSAGE);
            
        backToMainPage();
    }//GEN-LAST:event_jButtonSaveActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JComboBox<String> jComboBoxType;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextFieldAddress;
    private javax.swing.JTextField jTextFieldBalance;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldFN;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldLN;
    private javax.swing.JTextField jTextFieldPhone;
    private javax.swing.JTextField jTextFieldPsw;
    // End of variables declaration//GEN-END:variables
}
